#!/bin/sh
set -e

chown root:root /usr/bin/oxide-ce-bin
chmod 755 /usr/bin/oxide-ce-bin
chown root:root /usr/bin/oxide-ce
chmod 755 /usr/bin/oxide-ce
chown -R root:root /usr/lib/oxide
chmod 644 /usr/lib/oxide/libhypersecurity.so
chmod 644 /usr/lib/oxide/liboxide_proxy.so
chown -R root:root /usr/share/applications/oxide-ce.desktop
chmod 644 /usr/share/applications/oxide-ce.desktop
chown -R root:root /usr/share/icons/hicolor
chmod 644 /usr/share/icons/hicolor/scalable/apps/oxide-community.svg
chmod 644 /usr/share/icons/hicolor/64x64/apps/oxide-community.svg
chmod 644 /usr/share/icons/hicolor/128x128/apps/oxide-community.svg
chmod 644 /usr/share/icons/hicolor/256x256/apps/oxide-community.svg
chmod 644 /usr/share/oxide/banner
chown -R root:root /usr/share/oxide
chown -R root:root /usr/share/pixmaps/oxide-community.svg
chmod 644 /usr/share/pixmaps/oxide-community.svg
chown -R root:root /usr/share/man/man1/oxide.1.gz
chmod 644 /usr/share/man/man1/oxide.1.gz

ldconfig 2>/dev/null || true

if command -v mandb >/dev/null 2>&1; then
  mandb -q || true
fi

if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database || true
fi

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  gtk-update-icon-cache -f /usr/share/icons/hicolor || true
fi

exit 0
